export { LearningRecommendationEngine } from "./learningEngine";
export { GestureDifficultyAnalyzer, computeDifficultyScore } from "./gestureDifficulty";
export { ConversationInsights } from "./conversationInsights";
export type { ConversationInsightMetrics, SessionRecord } from "./conversationInsights";
export { ConversationCoach } from "./conversationCoach";
export type { GestureCoachData } from "./conversationCoach";
export { ErrorAnalysisEngine, globalErrorAnalysis } from "./errorAnalysis";
export type { LowConfidenceRecord, ConfusionPair, UnstableGesture, EnvironmentalTrend, WeeklyReport } from "./errorAnalysis";
export { DatasetExpansionEngine, globalDatasetExpansion } from "./datasetExpansion";
export type { GestureSampleNeed, GestureMetrics } from "./datasetExpansion";
export { DatasetQualityInspector, globalQualityInspector } from "./datasetQuality";
export type { QualityScore, VideoSample } from "./datasetQuality";
export { GestureClusteringEngine, globalClusteringEngine } from "./gestureClustering";
export type { GestureSample, GestureCluster } from "./gestureClustering";
export { DriftDetector, globalDriftDetector } from "./driftDetection";
export type { DriftAlert, DriftSnapshot } from "./driftDetection";
export { RetrainingManager, globalRetrainingManager } from "./retrainingManager";
export type { RetrainingStage, CandidateModel, RetrainingWorkflow } from "./retrainingManager";
