-- 0014_fsl105_gestures.sql
-- Registers all 133 model labels (28 alphabet + 105 FSL-105) in the gestures table.
-- Idempotent: uses on conflict (label) do nothing.

insert into public.gestures (label, description, display_order, is_active, status)
values
  -- Alphabet + Filipino letters (28)
  ('a', 'FSL letter A — closed fist with thumb at side', 1, true, 'approved'),
  ('b', 'FSL letter B — flat palm facing forward, fingers together', 2, true, 'approved'),
  ('c', 'FSL letter C — curved hand forming a C shape', 3, true, 'approved'),
  ('d', 'FSL letter D — index finger up, other fingers touch thumb', 4, true, 'approved'),
  ('e', 'FSL letter E — bent fingers touching thumb', 5, true, 'approved'),
  ('f', 'FSL letter F — index and thumb form a circle, other fingers up', 6, true, 'approved'),
  ('g', 'FSL letter G — index finger pointing sideways, thumb above', 7, true, 'approved'),
  ('h', 'FSL letter H — index and middle fingers extended sideways', 8, true, 'approved'),
  ('i', 'FSL letter I — pinky finger up, others closed', 9, true, 'approved'),
  ('j', 'FSL letter J — pinky up, draw a J motion', 10, true, 'approved'),
  ('k', 'FSL letter K — index up, middle out, thumb between', 11, true, 'approved'),
  ('l', 'FSL letter L — thumb and index form an L shape', 12, true, 'approved'),
  ('m', 'FSL letter M — three fingers over thumb', 13, true, 'approved'),
  ('n', 'FSL letter N — two fingers over thumb', 14, true, 'approved'),
  ('ñ', 'FSL letter Ñ — variant of N with tilde', 15, true, 'approved'),
  ('ng', 'FSL digraph NG — thumb and index form a circle, other fingers spread', 16, true, 'approved'),
  ('o', 'FSL letter O — fingertips meet thumb in a circle', 17, true, 'approved'),
  ('p', 'FSL letter P — like K but pointing down', 18, true, 'approved'),
  ('q', 'FSL letter Q — like G but pointing down', 19, true, 'approved'),
  ('r', 'FSL letter R — index and middle crossed', 20, true, 'approved'),
  ('s', 'FSL letter S — closed fist with thumb in front', 21, true, 'approved'),
  ('t', 'FSL letter T — thumb between index and middle', 22, true, 'approved'),
  ('u', 'FSL letter U — index and middle up together', 23, true, 'approved'),
  ('v', 'FSL letter V — index and middle up in a V', 24, true, 'approved'),
  ('w', 'FSL letter W — index, middle, and ring fingers up', 25, true, 'approved'),
  ('x', 'FSL letter X — index finger bent like a hook', 26, true, 'approved'),
  ('y', 'FSL letter Y — thumb and pinky out, others closed', 27, true, 'approved'),
  ('z', 'FSL letter Z — index draws a Z in the air', 28, true, 'approved'),

  -- FSL-105: GREETING (10)
  ('GOOD MORNING', 'Filipino Sign Language greeting for Good Morning', 101, true, 'approved'),
  ('GOOD AFTERNOON', 'Filipino Sign Language greeting for Good Afternoon', 102, true, 'approved'),
  ('GOOD EVENING', 'Filipino Sign Language greeting for Good Evening', 103, true, 'approved'),
  ('HELLO', 'Filipino Sign Language greeting for Hello', 104, true, 'approved'),
  ('HOW ARE YOU', 'Filipino Sign Language phrase for How Are You', 105, true, 'approved'),
  ('IM FINE', 'Filipino Sign Language phrase for I\'m Fine', 106, true, 'approved'),
  ('NICE TO MEET YOU', 'Filipino Sign Language phrase for Nice to Meet You', 107, true, 'approved'),
  ('THANK YOU', 'Filipino Sign Language phrase for Thank You', 108, true, 'approved'),
  ('YOURE WELCOME', 'Filipino Sign Language phrase for You\'re Welcome', 109, true, 'approved'),
  ('SEE YOU TOMORROW', 'Filipino Sign Language phrase for See You Tomorrow', 110, true, 'approved'),

  -- FSL-105: SURVIVAL (10)
  ('UNDERSTAND', 'Filipino Sign Language sign for Understand', 201, true, 'approved'),
  ('DON\'T UNDERSTAND', 'Filipino Sign Language sign for Don\'t Understand', 202, true, 'approved'),
  ('KNOW', 'Filipino Sign Language sign for Know', 203, true, 'approved'),
  ('DON\'T KNOW', 'Filipino Sign Language sign for Don\'t Know', 204, true, 'approved'),
  ('NO', 'Filipino Sign Language sign for No', 205, true, 'approved'),
  ('YES', 'Filipino Sign Language sign for Yes', 206, true, 'approved'),
  ('WRONG', 'Filipino Sign Language sign for Wrong', 207, true, 'approved'),
  ('CORRECT', 'Filipino Sign Language sign for Correct', 208, true, 'approved'),
  ('SLOW', 'Filipino Sign Language sign for Slow', 209, true, 'approved'),
  ('FAST', 'Filipino Sign Language sign for Fast', 210, true, 'approved'),

  -- FSL-105: NUMBER (10)
  ('ONE', 'Filipino Sign Language number One', 301, true, 'approved'),
  ('TWO', 'Filipino Sign Language number Two', 302, true, 'approved'),
  ('THREE', 'Filipino Sign Language number Three', 303, true, 'approved'),
  ('FOUR', 'Filipino Sign Language number Four', 304, true, 'approved'),
  ('FIVE', 'Filipino Sign Language number Five', 305, true, 'approved'),
  ('SIX', 'Filipino Sign Language number Six', 306, true, 'approved'),
  ('SEVEN', 'Filipino Sign Language number Seven', 307, true, 'approved'),
  ('EIGHT', 'Filipino Sign Language number Eight', 308, true, 'approved'),
  ('NINE', 'Filipino Sign Language number Nine', 309, true, 'approved'),
  ('TEN', 'Filipino Sign Language number Ten', 310, true, 'approved'),

  -- FSL-105: CALENDAR (12)
  ('JANUARY', 'Filipino Sign Language sign for January', 401, true, 'approved'),
  ('FEBRUARY', 'Filipino Sign Language sign for February', 402, true, 'approved'),
  ('MARCH', 'Filipino Sign Language sign for March', 403, true, 'approved'),
  ('APRIL', 'Filipino Sign Language sign for April', 404, true, 'approved'),
  ('MAY', 'Filipino Sign Language sign for May', 405, true, 'approved'),
  ('JUNE', 'Filipino Sign Language sign for June', 406, true, 'approved'),
  ('JULY', 'Filipino Sign Language sign for July', 407, true, 'approved'),
  ('AUGUST', 'Filipino Sign Language sign for August', 408, true, 'approved'),
  ('SEPTEMBER', 'Filipino Sign Language sign for September', 409, true, 'approved'),
  ('OCTOBER', 'Filipino Sign Language sign for October', 410, true, 'approved'),
  ('NOVEMBER', 'Filipino Sign Language sign for November', 411, true, 'approved'),
  ('DECEMBER', 'Filipino Sign Language sign for December', 412, true, 'approved'),

  -- FSL-105: DAYS (10)
  ('MONDAY', 'Filipino Sign Language sign for Monday', 501, true, 'approved'),
  ('TUESDAY', 'Filipino Sign Language sign for Tuesday', 502, true, 'approved'),
  ('WEDNESDAY', 'Filipino Sign Language sign for Wednesday', 503, true, 'approved'),
  ('THURSDAY', 'Filipino Sign Language sign for Thursday', 504, true, 'approved'),
  ('FRIDAY', 'Filipino Sign Language sign for Friday', 505, true, 'approved'),
  ('SATURDAY', 'Filipino Sign Language sign for Saturday', 506, true, 'approved'),
  ('SUNDAY', 'Filipino Sign Language sign for Sunday', 507, true, 'approved'),
  ('TODAY', 'Filipino Sign Language sign for Today', 508, true, 'approved'),
  ('TOMORROW', 'Filipino Sign Language sign for Tomorrow', 509, true, 'approved'),
  ('YESTERDAY', 'Filipino Sign Language sign for Yesterday', 510, true, 'approved'),

  -- FSL-105: FAMILY (10)
  ('FATHER', 'Filipino Sign Language sign for Father', 601, true, 'approved'),
  ('MOTHER', 'Filipino Sign Language sign for Mother', 602, true, 'approved'),
  ('SON', 'Filipino Sign Language sign for Son', 603, true, 'approved'),
  ('DAUGHTER', 'Filipino Sign Language sign for Daughter', 604, true, 'approved'),
  ('GRANDFATHER', 'Filipino Sign Language sign for Grandfather', 605, true, 'approved'),
  ('GRANDMOTHER', 'Filipino Sign Language sign for Grandmother', 606, true, 'approved'),
  ('UNCLE', 'Filipino Sign Language sign for Uncle', 607, true, 'approved'),
  ('AUNTIE', 'Filipino Sign Language sign for Auntie', 608, true, 'approved'),
  ('COUSIN', 'Filipino Sign Language sign for Cousin', 609, true, 'approved'),
  ('PARENTS', 'Filipino Sign Language sign for Parents', 610, true, 'approved'),

  -- FSL-105: RELATIONSHIPS (10)
  ('BOY', 'Filipino Sign Language sign for Boy', 701, true, 'approved'),
  ('GIRL', 'Filipino Sign Language sign for Girl', 702, true, 'approved'),
  ('MAN', 'Filipino Sign Language sign for Man', 703, true, 'approved'),
  ('WOMAN', 'Filipino Sign Language sign for Woman', 704, true, 'approved'),
  ('DEAF', 'Filipino Sign Language sign for Deaf', 705, true, 'approved'),
  ('HARD OF HEARING', 'Filipino Sign Language sign for Hard of Hearing', 706, true, 'approved'),
  ('WEELCHAIR PERSON', 'Filipino Sign Language sign for Wheelchair Person', 707, true, 'approved'),
  ('BLIND', 'Filipino Sign Language sign for Blind', 708, true, 'approved'),
  ('DEAF BLIND', 'Filipino Sign Language sign for Deaf-Blind', 709, true, 'approved'),
  ('MARRIED', 'Filipino Sign Language sign for Married', 710, true, 'approved'),

  -- FSL-105: COLOR (13)
  ('BLUE', 'Filipino Sign Language sign for Blue', 801, true, 'approved'),
  ('GREEN', 'Filipino Sign Language sign for Green', 802, true, 'approved'),
  ('RED', 'Filipino Sign Language sign for Red', 803, true, 'approved'),
  ('BROWN', 'Filipino Sign Language sign for Brown', 804, true, 'approved'),
  ('BLACK', 'Filipino Sign Language sign for Black', 805, true, 'approved'),
  ('WHITE', 'Filipino Sign Language sign for White', 806, true, 'approved'),
  ('YELLOW', 'Filipino Sign Language sign for Yellow', 807, true, 'approved'),
  ('ORANGE', 'Filipino Sign Language sign for Orange', 808, true, 'approved'),
  ('GRAY', 'Filipino Sign Language sign for Gray', 809, true, 'approved'),
  ('PINK', 'Filipino Sign Language sign for Pink', 810, true, 'approved'),
  ('VIOLET', 'Filipino Sign Language sign for Violet', 811, true, 'approved'),
  ('LIGHT', 'Filipino Sign Language sign for Light', 812, true, 'approved'),
  ('DARK', 'Filipino Sign Language sign for Dark', 813, true, 'approved'),

  -- FSL-105: FOOD (10)
  ('BREAD', 'Filipino Sign Language sign for Bread', 901, true, 'approved'),
  ('EGG', 'Filipino Sign Language sign for Egg', 902, true, 'approved'),
  ('FISH', 'Filipino Sign Language sign for Fish', 903, true, 'approved'),
  ('MEAT', 'Filipino Sign Language sign for Meat', 904, true, 'approved'),
  ('CHICKEN', 'Filipino Sign Language sign for Chicken', 905, true, 'approved'),
  ('SPAGHETTI', 'Filipino Sign Language sign for Spaghetti', 906, true, 'approved'),
  ('RICE', 'Filipino Sign Language sign for Rice', 907, true, 'approved'),
  ('LONGANISA', 'Filipino Sign Language sign for Longanisa', 908, true, 'approved'),
  ('SHRIMP', 'Filipino Sign Language sign for Shrimp', 909, true, 'approved'),
  ('CRAB', 'Filipino Sign Language sign for Crab', 910, true, 'approved'),

  -- FSL-105: DRINK (10)
  ('HOT', 'Filipino Sign Language sign for Hot', 1001, true, 'approved'),
  ('COLD', 'Filipino Sign Language sign for Cold', 1002, true, 'approved'),
  ('JUICE', 'Filipino Sign Language sign for Juice', 1003, true, 'approved'),
  ('MILK', 'Filipino Sign Language sign for Milk', 1004, true, 'approved'),
  ('COFFEE', 'Filipino Sign Language sign for Coffee', 1005, true, 'approved'),
  ('TEA', 'Filipino Sign Language sign for Tea', 1006, true, 'approved'),
  ('BEER', 'Filipino Sign Language sign for Beer', 1007, true, 'approved'),
  ('WINE', 'Filipino Sign Language sign for Wine', 1008, true, 'approved'),
  ('SUGAR', 'Filipino Sign Language sign for Sugar', 1009, true, 'approved'),
  ('NO SUGAR', 'Filipino Sign Language sign for No Sugar', 1010, true, 'approved')
on conflict (label) do nothing;
