-- 0026_phase20_feedback_intelligence.sql
-- Phase 20: User Feedback Intelligence & AI Assistant

-- Extended feedback with categorization
alter table public.feedback 
  add column if not exists feedback_category text check (feedback_category in ('recognition_error', 'wrong_translation', 'missing_gesture', 'ui_issue', 'performance', 'other')),
  add column if not exists severity text check (severity in ('low', 'medium', 'high', 'critical')),
  add column if not exists context_json jsonb;

create index if not exists feedback_category_idx on public.feedback(feedback_category);
create index if not exists feedback_severity_idx on public.feedback(severity);

-- Feedback summaries generated by AI
create table if not exists public.feedback_summaries (
  id uuid primary key default gen_random_uuid(),
  period text not null check (period in ('daily', 'weekly', 'monthly')),
  period_start date not null,
  period_end date not null,
  summary_text text not null,
  key_issues jsonb not null default '[]'::jsonb,
  recommendations jsonb not null default '[]'::jsonb,
  total_feedback_count integer not null default 0,
  created_at timestamptz not null default now(),
  unique(period, period_start)
);

alter table public.feedback_summaries enable row level security;

drop policy if exists "Admins read feedback summaries" on public.feedback_summaries;
create policy "Admins read feedback summaries" on public.feedback_summaries
  for select using (public.is_admin());

-- Admin AI Assistant conversation history
create table if not exists public.admin_ai_conversations (
  id uuid primary key default gen_random_uuid(),
  admin_id uuid not null references public.profiles(id) on delete cascade,
  question text not null,
  answer text not null,
  context_used jsonb,
  model_used text,
  tokens_used integer,
  created_at timestamptz not null default now()
);

create index if not exists admin_ai_conversations_admin_idx on public.admin_ai_conversations(admin_id);
create index if not exists admin_ai_conversations_created_idx on public.admin_ai_conversations(created_at);

alter table public.admin_ai_conversations enable row level security;

drop policy if exists "Admins manage own AI conversations" on public.admin_ai_conversations;
create policy "Admins manage own AI conversations" on public.admin_ai_conversations
  for all using (auth.uid() = admin_id);
