import {
  Keyboard,
  Video,
  Hand,
  BookOpen,
  Search,
  ArrowUpRight,
  AlertCircle,
  CheckCircle,
  XCircle,
  Copy,
  Download,
  RefreshCw,
  Settings,
  HelpCircle,
  Camera,
  Mic,
  Speaker,
  Trash2,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  Home,
  ExternalLink,
  Eye,
  EyeOff,
  Volume2,
  VolumeX,
  Wifi,
  WifiOff,
  Loader2,
  Zap,
  Sparkles,
  Brain,
  Heart,
  Star,
  Flag,
  Bell,
  BellOff,
  Moon,
  Sun,
  Menu,
  X,
  Plus,
  Minus,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  Check,
  Circle,
  Square,
  Triangle,
  Hexagon,
  Pentagon,
  Octagon,
  Diamond,
  Crosshair,
  Target,
  Scan,
  Filter,
  SortAsc,
  SortDesc,
  Grid,
  List,
  Layers,
  Box,
  Package,
  File,
  FileText,
  Image,
  Code,
  Terminal,
  Database,
  Server,
  Cloud,
  Globe,
  Mail,
  Phone,
  MapPin,
  Calendar,
  Clock,
  Timer,
  Activity,
  HeartPulse,
  BrainCircuit,
  Cpu,
  HardDrive,
  MemoryStick,
  Monitor,
  Smartphone,
  Tablet,
  Laptop,
  Watch,
  Headphones,
  Mic2,
  Printer,
  Mouse,
  Gamepad,
  Joystick,
  Disc,
  Usb,
  Bluetooth,
  Battery,
  Power,
  Lock,
  Unlock,
  Key,
  Shield,
  AlertTriangle,
  Info,
  MessageCircle,
  MessageSquare,
  Send,
  Reply,
  Forward,
  Share2,
  Link,
  Unlink,
  AtSign,
  Hash,
  DollarSign,
  Euro,
  Bitcoin,
  CreditCard,
  Receipt,
  Calculator,
  Briefcase,
  ShoppingCart,
  ShoppingBag,
  Gift,
  Ticket,
  IdCard,
  Badge,
  Award,
  Medal,
  Trophy,
  Crown,
  Gem,
  Wand,
  Palette,
  Brush,
  Pen,
  Pencil,
  Eraser,
  Highlighter,
  Text,
  Type,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  AlignLeft,
  AlignCenter,
  AlignRight,
  AlignJustify,
  ListOrdered,
  Indent,
  Outdent,
  MoreHorizontal,
  MoreVertical,
} from "lucide-react";

export const icons = {
  navigation: {
    home: Home,
    menu: Menu,
    chevronLeft: ChevronLeft,
    chevronRight: ChevronRight,
    chevronUp: ChevronUp,
    chevronDown: ChevronDown,
    arrowLeft: ArrowLeft,
    arrowRight: ArrowRight,
    arrowUp: ArrowUp,
    arrowDown: ArrowDown,
    externalLink: ExternalLink,
  },
  actions: {
    copy: Copy,
    download: Download,
    refresh: RefreshCw,
    settings: Settings,
    help: HelpCircle,
    delete: Trash2,
    add: Plus,
    remove: Minus,
    check: Check,
    close: X,
    search: Search,
    filter: Filter,
    sortAsc: SortAsc,
    sortDesc: SortDesc,
    share: Share2,
    link: Link,
    unlink: Unlink,
  },
  media: {
    camera: Camera,
    mic: Mic,
    micOff: Mic2,
    speaker: Speaker,
    volumeUp: Volume2,
    volumeMute: VolumeX,
    video: Video,
    image: Image,
  },
  status: {
    success: CheckCircle,
    error: XCircle,
    warning: AlertTriangle,
    info: Info,
    loading: Loader2,
    wifi: Wifi,
    wifiOff: WifiOff,
    bluetooth: Bluetooth,
    battery: Battery,
    power: Power,
    lock: Lock,
    unlock: Unlock,
    shield: Shield,
    alert: AlertCircle,
    bell: Bell,
    bellOff: BellOff,
  },
  translation: {
    keyboard: Keyboard,
    video: Video,
    signToText: Video,
    textToSign: Keyboard,
    fingerspell: Sparkles,
    translate: Zap,
    language: Globe,
    speech: Mic,
    speak: Volume2,
  },
  learning: {
    hand: Hand,
    book: BookOpen,
    video: Video,
    practice: Target,
    quiz: HelpCircle,
    progress: Activity,
    achievement: Award,
    star: Star,
    heart: Heart,
    flag: Flag,
  },
  ui: {
    grid: Grid,
    list: List,
    layers: Layers,
    box: Box,
    eye: Eye,
    eyeOff: EyeOff,
    expand: ChevronDown,
    collapse: ChevronUp,
    fullscreen: ArrowUpRight,
    minimize: ArrowDown,
    maximize: ArrowUpRight,
    close: X,
    menu: Menu,
    more: MoreHorizontal,
    less: MoreVertical,
  },
  shapes: {
    circle: Circle,
    square: Square,
    triangle: Triangle,
    hexagon: Hexagon,
    pentagon: Pentagon,
    octagon: Octagon,
    diamond: Diamond,
    crosshair: Crosshair,
    target: Target,
    scan: Scan,
  },
  development: {
    code: Code,
    terminal: Terminal,
    database: Database,
    server: Server,
    cloud: Cloud,
    globe: Globe,
    network: Wifi,
    cpu: Cpu,
    memory: MemoryStick,
    storage: HardDrive,
    monitor: Monitor,
    mobile: Smartphone,
    tablet: Tablet,
    laptop: Laptop,
  },
  text: {
    bold: Bold,
    italic: Italic,
    underline: Underline,
    strikethrough: Strikethrough,
    type: Type,
    text: Text,
    alignLeft: AlignLeft,
    alignCenter: AlignCenter,
    alignRight: AlignRight,
    alignJustify: AlignJustify,
    list: List,
    listOrdered: ListOrdered,
    indent: Indent,
    outdent: Outdent,
  },
} as const;

export type IconCategory = keyof typeof icons;
export type IconName<T extends IconCategory> = keyof typeof icons[T];

export function getIcon<T extends IconCategory>(category: T, name: IconName<T>) {
  return icons[category][name];
}

export const iconSizes = {
  xs: "h-3 w-3",
  sm: "h-4 w-4",
  md: "h-5 w-5",
  lg: "h-6 w-6",
  xl: "h-8 w-8",
  "2xl": "h-10 w-10",
  "3xl": "h-12 w-12",
} as const;

export type IconSize = keyof typeof iconSizes;

export function getIconSize(size: IconSize): string {
  return iconSizes[size];
}